#!/usr/bin/env python3
"""Maintain Skillry's repository-only Gemini and Copilot instruction adapters.

AGENTS.md and CLAUDE.md are equivalent, hand-maintained contributor entry points.
This tool never writes either one or copies their policy into another project.
The old Factory candidate files remain historical evidence, not adapter input.
Dry-run is the default; --check checks freshness without writes; --apply updates
only the two adapters in this repository. This tool is not installer payload.
"""
from __future__ import annotations

import argparse
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
GENERATED = "<!-- GENERATED by tools/build-agent-instructions.py — do not edit directly. -->"
TARGETS = {
    "GEMINI.md": ("Gemini CLI and Google Antigravity", "AGENTS.md", "CLAUDE.md"),
    ".github/copilot-instructions.md": ("GitHub Copilot", "../AGENTS.md", "../CLAUDE.md"),
}


def shared_body(text: str, name: str) -> str:
    match = re.search(r"^## ", text, re.M)
    if not match:
        raise ValueError(f"{name}: contributor sections are missing")
    return text[match.start():].strip()


def render() -> dict[str, str]:
    # Check both canonical files before planning any output. Never regenerate
    # them to conceal a policy mismatch or reactivate legacy Factory policy.
    bodies = {
        name: shared_body((ROOT / name).read_text(encoding="utf-8"), name)
        for name in ("AGENTS.md", "CLAUDE.md")
    }
    if bodies["AGENTS.md"] != bodies["CLAUDE.md"]:
        raise ValueError("AGENTS.md and CLAUDE.md contributor rules differ; reconcile their source")
    return {
        path: (
            f"# {assistant} — Skillry repository adapter\n\n"
            f"{GENERATED}\n\n"
            f"Read and follow [AGENTS.md]({agents}) before working in this repository.\n"
            f"[CLAUDE.md]({claude}) is an equivalent contributor entry point; neither\n"
            "file creates a higher policy layer. This adapter adds no separate rules.\n\n"
            "These instructions apply only to contributions to Skillry. They are not\n"
            "portable installer payload and must not be copied into other projects.\n"
            "The portable installer installs skills and agents only.\n"
        )
        for path, (assistant, agents, claude) in TARGETS.items()
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true", help="update repository adapters")
    mode.add_argument("--check", action="store_true", help="fail on missing or stale adapters; no writes")
    args = parser.parse_args()
    try:
        outputs = render()
    except (OSError, ValueError) as exc:
        parser.exit(1, f"repository adapters: {exc}\n")
    stale = []
    for relative, content in outputs.items():
        target = ROOT / relative
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current != content:
            stale.append(relative)
        print(f"{'STALE' if current != content else 'OK'} {relative}")
        if args.apply:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
    if args.check and stale:
        parser.exit(1, "Run python3 tools/build-agent-instructions.py --apply to refresh repository adapters.\n")
    if not args.apply:
        print("No files written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
